language: python
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=Django==2.2
  - DJANGO=--pre Django
install:
  - pip install -q -r requirements.txt
  - pip install -q $DJANGO
script:
  - python happenings/manage.py test