language: python
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3
install:
  - pip install -q -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - python happenings/manage.py test