version: '3.7'

services:
    web:
        build: ./happenings
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./happenings/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./happenings/.env.dev