# Generated by Django 2.2.6 on 2019-10-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Happening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=320)),
                ('happening', models.ForeignKey(on_delete='CASCADE', to='app.Happening')),
            ],
        ),
        migrations.AddField(
            model_name='happening',
            name='tags',
            field=models.ForeignKey(on_delete='NULL', to='app.Tag'),
        ),
    ]
