# Generated by Django 2.2.6 on 2019-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191016_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='happening',
            name='tags',
        ),
        migrations.AddField(
            model_name='happening',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
