# Generated by Django 2.2.6 on 2019-11-05 02:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191020_2246'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='happening',
            managers=[
                ('happenings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='happening',
            name='text',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
